<?php

namespace Niji\AutoAttributeOptionsSetterBundle;

use Akeneo\Tool\Bundle\StorageUtilsBundle\DependencyInjection\Compiler\ResolveDoctrineTargetRepositoryPass;
use Niji\AutoAttributeOptionsSetterBundle\DependencyInjection\Compiler\AttributeOptionCompilerPass;
use Niji\AutoAttributeOptionsSetterBundle\DependencyInjection\Compiler\PropertySetterCompilerPass;
use Symfony\Component\DependencyInjection\Compiler\PassConfig;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class AutoAttributeOptionsSetterBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $container->addCompilerPass(new AttributeOptionCompilerPass());
        $container->addCompilerPass(new PropertySetterCompilerPass(),PassConfig::TYPE_BEFORE_REMOVING);
        $container->addCompilerPass(new ResolveDoctrineTargetRepositoryPass('pim_niji_attribute_repository'));
    }
}
